name: Deploy Elymica Portals

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  PNPM_VERSION: '8.15.0'

jobs:
  deploy:
    name: Deploy ${{ matrix.portal.name }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: deploy-portals
      cancel-in-progress: true
    strategy:
      matrix:
        portal:
          - name: Student Portal
            dir: apps/student-portal
          - name: Parent Portal
            dir: apps/parent-portal
          - name: Teacher Portal
            dir: apps/teacher-portal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install workspace dependencies
        run: pnpm install --frozen-lockfile

      - name: Build ${{ matrix.portal.name }}
        working-directory: ${{ matrix.portal.dir }}
        run: pnpm run build:cloudflare

      - name: Deploy ${{ matrix.portal.name }}
        working-directory: ${{ matrix.portal.dir }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: pnpm wrangler deploy --env=production
